name: cmpdiri4
description: "Major Project for CMPDI RI4"
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Core Packages
  flutter_riverpod: ^2.5.1
  dio: ^5.4.3+1
  flutter_secure_storage: ^9.2.2
  video_player: ^2.8.6

  # Data Serialization & Models
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1
  intl: ^0.19.0

  # UI
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.3.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  geocoding: ^3.0.0
  flutter_polyline_points: ^2.0.0
  geolocator: ^12.0.0
  flutter_map_dragmarker: ^6.0.0
  syncfusion_flutter_datepicker: ^26.1.41
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/cmpdi_ri4_app_logo.png"
  adaptive_icon_background: "#D1E9F9"

flutter:
  uses-material-design: true
  assets:
    - assets/
